In [ ]:
import numpy as np
import pandas as pd
data=pd.read_csv("pandas_practice_dataset.csv")
data.to_csv("pandas_practice_dataset.csv")
data.head(5)

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,Matches,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
0,0,0,0,0,Azmatullah Omarzai,9,5,1,63,28,...,0,0,9,1,2,0,5,52.40,4.85,2
1,1,1,1,1,Fareed Ahmad,14,5,4,20,13,...,0,0,0,1,3,0,19,23.94,4.94,9
2,2,2,2,2,Fazalhaq Farooqi,13,5,3,6,4,...,0,0,1,0,1,0,19,28.31,5.42,1
3,3,3,3,3,Gulbadin Naib,76,65,8,1170,82*,...,0,5,94,28,22,0,65,35.35,5.43,12
4,4,4,4,4,Hashmatullah Shahidi,56,56,7,1604,97*,...,0,14,139,9,12,0,0,0.00,8.33,5

In [ ]:
data.tail(3)

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,Matches,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
218,218,218,218,220,Mark Watt,54,34,11,371,37*,...,0,0,27,4,13,0,79,23.97,4.04,8
219,219,219,219,221,Chris Sole,23,11,1,47,15,...,0,0,5,0,5,0,42,23.33,5.17,4
220,220,220,220,222,Amir Hamza,31,16,9,23,7,...,0,0,0,1,10,0,40,25.40,3.92,5

In [ ]:
data.info(6)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.3  221 non-null    int64
 1   Unnamed: 0.2  221 non-null    int64
 2   Unnamed: 0.1  221 non-null    int64
 3   Unnamed: 0    221 non-null    int64
 4   Player Name   221 non-null    object
 5   Matches       221 non-null    int64
 6   Innings       221 non-null    int64
 7   Not Outs      221 non-null    int64
 8   Runs          221 non-null    int64
 9   High Score    221 non-null    object
 10  Average       221 non-null    int64
 11  Balls Faced   221 non-null    int64
 12  Strike rate   221 non-null    float64
 13  100s          221 non-null    int64
 14  50s           221 non-null    int64
 15  4s            221 non-null    int64
 16  6s            221 non-null    int64
 17  Catches       221 non-null    int64
 18  Stumps        221 non-null    int64
 19  Wkts          221 non-null    int64
 20  Ave           221 non-null    float64
 21  Econ          221 non-null    float64
 22  Span(years)   221 non-null    int64
dtypes: float64(3), int64(18), object(2)
memory usage: 39.8+ KB

In [ ]:
data.describe()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Matches,Innings,Not Outs,Runs,Average,Balls Faced,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
count,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.00000,221.000000,221.000000,...,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000
mean,110.000000,110.000000,110.000000,111.343891,59.429864,48.248869,8.502262,1373.00000,26.529412,1587.027149,...,2.384615,7.443439,125.289593,25.701357,25.325792,0.950226,36.696833,28.496199,4.332851,6.429864
std,63.941379,63.941379,63.941379,64.671894,55.520683,52.317619,9.269022,2009.20342,15.837679,2305.232881,...,5.389513,11.804957,192.661944,38.355650,32.553072,4.661473,49.949278,24.390757,2.449393,3.322214
min,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,2.00000,0.000000,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,55.000000,55.000000,55.000000,56.000000,19.000000,12.000000,2.000000,143.00000,13.000000,178.000000,...,0.000000,0.000000,11.000000,2.000000,5.000000,0.000000,0.000000,0.000000,4.170000,4.000000
50%,110.000000,110.000000,110.000000,112.000000,43.000000,28.000000,6.000000,542.00000,26.000000,684.000000,...,0.000000,2.000000,47.000000,10.000000,14.000000,0.000000,16.000000,28.280000,5.150000,6.000000
75%,165.000000,165.000000,165.000000,167.000000,81.000000,62.000000,11.000000,1604.00000,37.000000,1882.000000,...,2.000000,11.000000,152.000000,34.000000,33.000000,0.000000,52.000000,37.100000,5.620000,8.000000
max,220.000000,220.000000,220.000000,222.000000,274.000000,265.000000,50.000000,12898.00000,83.000000,13776.000000,...,46.000000,65.000000,1211.000000,275.000000,214.000000,53.000000,301.000000,166.250000,14.400000,16.000000

In [ ]:
data.shape

(221, 23)

In [ ]:
data.columns

Index(['Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0',
       'Player Name', 'Matches', 'Innings', 'Not Outs', 'Runs', 'High Score',
       'Average', 'Balls Faced', 'Strike rate', '100s', '50s', '4s', '6s',
       'Catches', 'Stumps', 'Wkts', 'Ave', 'Econ', 'Span(years)'],
      dtype='object')

In [ ]:
data.dtypes

Unnamed: 0.3      int64
Unnamed: 0.2      int64
Unnamed: 0.1      int64
Unnamed: 0        int64
Player Name      object
Matches           int64
Innings           int64
Not Outs          int64
Runs              int64
High Score       object
Average           int64
Balls Faced       int64
Strike rate     float64
100s              int64
50s               int64
4s                int64
6s                int64
Catches           int64
Stumps            int64
Wkts              int64
Ave             float64
Econ            float64
Span(years)       int64
dtype: object

In [ ]:
data['Stumps']

0      0
1      0
2      0
3      0
4      0
      ..
216    0
217    2
218    0
219    0
220    0
Name: Stumps, Length: 221, dtype: int64

In [ ]:
data[['Player Name','Matches']]

              Player Name  Matches
0      Azmatullah Omarzai        9
1            Fareed Ahmad       14
2        Fazalhaq Farooqi       13
3           Gulbadin Naib       76
4    Hashmatullah Shahidi       56
..                    ...      ...
216        Safyaan Sharif       71
217         Craig Wallace       32
218             Mark Watt       54
219            Chris Sole       23
220            Amir Hamza       31

[221 rows x 2 columns]

In [ ]:
data.loc[2,'Player Name']

'Fazalhaq Farooqi'

In [ ]:
data.iloc[2,5]

13

In [ ]:
data[data['Average']>21]

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,Matches,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
4,4,4,4,4,Hashmatullah Shahidi,56,56,7,1604,97*,...,0,14,139,9,12,0,0,0.00,8.33,5
5,5,5,5,5,Ibrahim Zadran,11,11,1,607,162,...,3,2,62,9,3,0,0,0.00,0.00,4
6,6,6,6,6,Mohammad Nabi,139,124,14,3020,116,...,1,15,195,92,58,0,147,32.18,4.30,1
8,8,8,8,8,Najibullah Zadran,85,78,13,1993,104*,...,1,15,173,66,39,0,0,0.00,6.00,9
10,10,10,10,10,Rahmanullah Gurbaz,18,18,1,606,127,...,3,2,53,25,12,2,0,0.00,0.00,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,210,210,210,212,Kyle Coetzer,89,87,5,3192,156,...,5,21,412,40,26,0,2,126.50,5.62,7
212,212,212,212,214,Michael Leask,62,51,10,1071,107*,...,1,6,84,48,26,0,52,33.46,5.03,8
213,213,213,213,215,Calum MacLeod,88,86,7,3026,175,...,10,13,312,35,53,0,11,76.00,5.18,8
214,214,214,214,216,Gavin Main,14,4,3,82,64*,...,0,1,7,1,7,0,30,18.96,5.26,2
215,215,215,215,217,George Munsey,49,48,9,1520,103*,...,1,11,156,41,22,0,0,0.00,0.00,5

In [ ]:
data.sort_values(by=['Average'])

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,Matches,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
98,98,98,98,100,Umran Malik,8,3,3,2,2*,...,0,0,0,0,1,0,13,27.30,6.45,1
45,45,45,45,45,Nasum Ahmed,7,2,2,29,18*,...,0,0,4,1,1,0,8,22.75,3.73,2
92,92,92,92,93,Prasidh Krishna,14,5,3,2,2*,...,0,0,0,0,2,0,25,23.92,5.32,1
31,31,31,31,31,Mitchell Swepson,3,1,0,2,2,...,0,0,0,0,0,0,3,53.66,6.11,2
36,36,36,36,36,Ebadot Hossain,11,6,4,3,1*,...,0,0,0,0,1,0,21,21.09,5.49,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,5,5,5,5,Ibrahim Zadran,11,11,1,607,162,...,3,2,62,9,3,0,0,0.00,0.00,4
96,96,96,96,98,Shubman Gill,24,24,4,1311,208,...,4,5,149,28,15,0,0,0.00,0.00,4
94,94,94,94,95,Sanju Samson,11,10,5,330,86*,...,0,2,25,15,7,2,0,0.00,0.00,9
214,214,214,214,216,Gavin Main,14,4,3,82,64*,...,0,1,7,1,7,0,30,18.96,5.26,2
46,46,46,46,46,Nurul Hasan,6,5,3,165,45*,...,0,0,15,3,4,3,0,0.00,0.00,2

In [ ]:
data.sort_index()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,Matches,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
0,0,0,0,0,Azmatullah Omarzai,9,5,1,63,28,...,0,0,9,1,2,0,5,52.40,4.85,2
1,1,1,1,1,Fareed Ahmad,14,5,4,20,13,...,0,0,0,1,3,0,19,23.94,4.94,9
2,2,2,2,2,Fazalhaq Farooqi,13,5,3,6,4,...,0,0,1,0,1,0,19,28.31,5.42,1
3,3,3,3,3,Gulbadin Naib,76,65,8,1170,82*,...,0,5,94,28,22,0,65,35.35,5.43,12
4,4,4,4,4,Hashmatullah Shahidi,56,56,7,1604,97*,...,0,14,139,9,12,0,0,0.00,8.33,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,216,216,216,218,Safyaan Sharif,71,49,23,526,40*,...,0,0,35,5,19,0,94,29.70,4.96,7
217,217,217,217,219,Craig Wallace,32,28,1,574,58,...,0,4,47,12,17,2,0,0.00,0.00,4
218,218,218,218,220,Mark Watt,54,34,11,371,37*,...,0,0,27,4,13,0,79,23.97,4.04,8
219,219,219,219,221,Chris Sole,23,11,1,47,15,...,0,0,5,0,5,0,42,23.33,5.17,4
220,220,220,220,222,Amir Hamza,31,16,9,23,7,...,0,0,0,1,10,0,40,25.40,3.92,5

In [ ]:
data.reset_index(drop=True)

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,Matches,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
0,0,0,0,0,Azmatullah Omarzai,9,5,1,63,28,...,0,0,9,1,2,0,5,52.40,4.85,2
1,1,1,1,1,Fareed Ahmad,14,5,4,20,13,...,0,0,0,1,3,0,19,23.94,4.94,9
2,2,2,2,2,Fazalhaq Farooqi,13,5,3,6,4,...,0,0,1,0,1,0,19,28.31,5.42,1
3,3,3,3,3,Gulbadin Naib,76,65,8,1170,82*,...,0,5,94,28,22,0,65,35.35,5.43,12
4,4,4,4,4,Hashmatullah Shahidi,56,56,7,1604,97*,...,0,14,139,9,12,0,0,0.00,8.33,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,216,216,216,218,Safyaan Sharif,71,49,23,526,40*,...,0,0,35,5,19,0,94,29.70,4.96,7
217,217,217,217,219,Craig Wallace,32,28,1,574,58,...,0,4,47,12,17,2,0,0.00,0.00,4
218,218,218,218,220,Mark Watt,54,34,11,371,37*,...,0,0,27,4,13,0,79,23.97,4.04,8
219,219,219,219,221,Chris Sole,23,11,1,47,15,...,0,0,5,0,5,0,42,23.33,5.17,4
220,220,220,220,222,Amir Hamza,31,16,9,23,7,...,0,0,0,1,10,0,40,25.40,3.92,5

In [ ]:
data.rename(columns={'Matches':'M'})

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,M,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
0,0,0,0,0,Azmatullah Omarzai,9,5,1,63,28,...,0,0,9,1,2,0,5,52.40,4.85,2
1,1,1,1,1,Fareed Ahmad,14,5,4,20,13,...,0,0,0,1,3,0,19,23.94,4.94,9
2,2,2,2,2,Fazalhaq Farooqi,13,5,3,6,4,...,0,0,1,0,1,0,19,28.31,5.42,1
3,3,3,3,3,Gulbadin Naib,76,65,8,1170,82*,...,0,5,94,28,22,0,65,35.35,5.43,12
4,4,4,4,4,Hashmatullah Shahidi,56,56,7,1604,97*,...,0,14,139,9,12,0,0,0.00,8.33,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,216,216,216,218,Safyaan Sharif,71,49,23,526,40*,...,0,0,35,5,19,0,94,29.70,4.96,7
217,217,217,217,219,Craig Wallace,32,28,1,574,58,...,0,4,47,12,17,2,0,0.00,0.00,4
218,218,218,218,220,Mark Watt,54,34,11,371,37*,...,0,0,27,4,13,0,79,23.97,4.04,8
219,219,219,219,221,Chris Sole,23,11,1,47,15,...,0,0,5,0,5,0,42,23.33,5.17,4
220,220,220,220,222,Amir Hamza,31,16,9,23,7,...,0,0,0,1,10,0,40,25.40,3.92,5

In [ ]:
data.drop(['Player Name','Matches'],axis=1)

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Innings,Not Outs,Runs,High Score,Average,Balls Faced,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
0,0,0,0,0,5,1,63,28,16,87,...,0,0,9,1,2,0,5,52.40,4.85,2
1,1,1,1,1,5,4,20,13,20,33,...,0,0,0,1,3,0,19,23.94,4.94,9
2,2,2,2,2,5,3,6,4,3,27,...,0,0,1,0,1,0,19,28.31,5.42,1
3,3,3,3,3,65,8,1170,82*,21,1593,...,0,5,94,28,22,0,65,35.35,5.43,12
4,4,4,4,4,56,7,1604,97*,33,2407,...,0,14,139,9,12,0,0,0.00,8.33,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,216,216,216,218,49,23,526,40*,20,727,...,0,0,35,5,19,0,94,29.70,4.96,7
217,217,217,217,219,28,1,574,58,21,630,...,0,4,47,12,17,2,0,0.00,0.00,4
218,218,218,218,220,34,11,371,37*,16,504,...,0,0,27,4,13,0,79,23.97,4.04,8
219,219,219,219,221,11,1,47,15,5,63,...,0,0,5,0,5,0,42,23.33,5.17,4
220,220,220,220,222,16,9,23,7,3,94,...,0,0,0,1,10,0,40,25.40,3.92,5

In [ ]:
data.fillna()5000000

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,Matches,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
0,0,0,0,0,Azmatullah Omarzai,9,5,1,63,28,...,0,0,9,1,2,0,5,52.40,4.85,2
1,1,1,1,1,Fareed Ahmad,14,5,4,20,13,...,0,0,0,1,3,0,19,23.94,4.94,9
2,2,2,2,2,Fazalhaq Farooqi,13,5,3,6,4,...,0,0,1,0,1,0,19,28.31,5.42,1
3,3,3,3,3,Gulbadin Naib,76,65,8,1170,82*,...,0,5,94,28,22,0,65,35.35,5.43,12
4,4,4,4,4,Hashmatullah Shahidi,56,56,7,1604,97*,...,0,14,139,9,12,0,0,0.00,8.33,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,216,216,216,218,Safyaan Sharif,71,49,23,526,40*,...,0,0,35,5,19,0,94,29.70,4.96,7
217,217,217,217,219,Craig Wallace,32,28,1,574,58,...,0,4,47,12,17,2,0,0.00,0.00,4
218,218,218,218,220,Mark Watt,54,34,11,371,37*,...,0,0,27,4,13,0,79,23.97,4.04,8
219,219,219,219,221,Chris Sole,23,11,1,47,15,...,0,0,5,0,5,0,42,23.33,5.17,4
220,220,220,220,222,Amir Hamza,31,16,9,23,7,...,0,0,0,1,10,0,40,25.40,3.92,5

In [ ]:
data.dropna()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,Matches,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
0,0,0,0,0,Azmatullah Omarzai,9,5,1,63,28,...,0,0,9,1,2,0,5,52.40,4.85,2
1,1,1,1,1,Fareed Ahmad,14,5,4,20,13,...,0,0,0,1,3,0,19,23.94,4.94,9
2,2,2,2,2,Fazalhaq Farooqi,13,5,3,6,4,...,0,0,1,0,1,0,19,28.31,5.42,1
3,3,3,3,3,Gulbadin Naib,76,65,8,1170,82*,...,0,5,94,28,22,0,65,35.35,5.43,12
4,4,4,4,4,Hashmatullah Shahidi,56,56,7,1604,97*,...,0,14,139,9,12,0,0,0.00,8.33,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,216,216,216,218,Safyaan Sharif,71,49,23,526,40*,...,0,0,35,5,19,0,94,29.70,4.96,7
217,217,217,217,219,Craig Wallace,32,28,1,574,58,...,0,4,47,12,17,2,0,0.00,0.00,4
218,218,218,218,220,Mark Watt,54,34,11,371,37*,...,0,0,27,4,13,0,79,23.97,4.04,8
219,219,219,219,221,Chris Sole,23,11,1,47,15,...,0,0,5,0,5,0,42,23.33,5.17,4
220,220,220,220,222,Amir Hamza,31,16,9,23,7,...,0,0,0,1,10,0,40,25.40,3.92,5

In [ ]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
216    False
217    False
218    False
219    False
220    False
Length: 221, dtype: bool

In [ ]:
data.drop_duplicates()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player Name,Matches,Innings,Not Outs,Runs,High Score,...,100s,50s,4s,6s,Catches,Stumps,Wkts,Ave,Econ,Span(years)
0,0,0,0,0,Azmatullah Omarzai,9,5,1,63,28,...,0,0,9,1,2,0,5,52.40,4.85,2
1,1,1,1,1,Fareed Ahmad,14,5,4,20,13,...,0,0,0,1,3,0,19,23.94,4.94,9
2,2,2,2,2,Fazalhaq Farooqi,13,5,3,6,4,...,0,0,1,0,1,0,19,28.31,5.42,1
3,3,3,3,3,Gulbadin Naib,76,65,8,1170,82*,...,0,5,94,28,22,0,65,35.35,5.43,12
4,4,4,4,4,Hashmatullah Shahidi,56,56,7,1604,97*,...,0,14,139,9,12,0,0,0.00,8.33,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,216,216,216,218,Safyaan Sharif,71,49,23,526,40*,...,0,0,35,5,19,0,94,29.70,4.96,7
217,217,217,217,219,Craig Wallace,32,28,1,574,58,...,0,4,47,12,17,2,0,0.00,0.00,4
218,218,218,218,220,Mark Watt,54,34,11,371,37*,...,0,0,27,4,13,0,79,23.97,4.04,8
219,219,219,219,221,Chris Sole,23,11,1,47,15,...,0,0,5,0,5,0,42,23.33,5.17,4
220,220,220,220,222,Amir Hamza,31,16,9,23,7,...,0,0,0,1,10,0,40,25.40,3.92,5

In [ ]:
data['Matches'].sum()

13134

In [ ]:
data['Matches'].mean()

59.42986425339367

In [ ]:
data['Matches'].min()

1

In [ ]:
data['Matches'].max()

274

In [ ]:
data['Matches'].value_counts()

Matches
14     7
9      6
11     6
18     6
28     5
      ..
42     1
10     1
167    1
5      1
71     1
Name: count, Length: 115, dtype: int64

In [ ]:
data.groupby('Matches').agg({'Average':'sum'})

         Average
Matches
1             19
3             59
4              6
5              7
6            133
...          ...
232           38
240           37
243           49
248           76
274           57

[115 rows x 1 columns]